// GR 223 — Mai 2026 · trek configuration
// One entry per day. Days without a GPX file render as "à venir" placeholders.

window.TREK = {
  name: 'GR 223',
  subtitle: 'Mai 2026',
  // Used to compute weekday names and date labels.
  startDate: '2026-05-05', // Day 1 = mardi 5 mai 2026

  // Palette: 22 distinct, harmonious hues (oklch ~58% L, 0.13 C, evenly spaced).
  // Same lightness across all so no day looks more important than another.
  palette: [
    '#c4544f', // 01 brique
    '#c46836', // 02 cuivre
    '#bf7920', // 03 ocre
    '#b08820', // 04 moutarde
    '#9b9220', // 05 olive
    '#809627', // 06 mousse
    '#609835', // 07 vert prairie
    '#479649', // 08 vert sapin
    '#329263', // 09 jade
    '#2e8d78', // 10 sarcelle profonde
    '#2e878b', // 11 sarcelle
    '#388099', // 12 bleu acier
    '#4677a4', // 13 bleu manche
    '#566cab', // 14 outremer
    '#6a60ad', // 15 violet
    '#8254a8', // 16 prune
    '#984a9c', // 17 améthyste
    '#aa4589', // 18 magenta
    '#b44674', // 19 framboise
    '#b64a5e', // 20 grenadine
    '#b25347', // 21 rouille
    '#a76045', // 22 terre brûlée
  ],

  days: [
    { num: 1, from: 'De Panne', to: 'Bergues', weather: null, gpx: 'data/01-de-panne-bergues.gpx',
      photos: [
        { file: 'photos/jour-01/01.jpg', km: 0.0,  caption: 'Devant la porte · départ à De Panne' },
        { file: 'photos/jour-01/02.jpg', km: 0.5,  caption: 'Statue de Léopold Ier · « Koning van België », arrivée en Belgique en 1831' },
        { file: 'photos/jour-01/03.jpg', km: 0.8,  caption: '« Ideally you would sea where to… » · drapeau sur la plage' },
        { file: 'photos/jour-01/04.jpg', km: 1.0,  caption: 'Selfie père-fils sur la plage de De Panne' },
        { file: 'photos/jour-01/05.jpg', km: 2.0,  caption: 'Balisage Kustwandelroute · GR 5A · GR 120 · sentier européen E9' },
        { file: 'photos/jour-01/06.jpg', km: 6.0,  caption: 'Estran à marée basse, ciel pommelé' },
        { file: 'photos/jour-01/07.jpg', km: 10.0, caption: 'Dunes et oyats · approche de la frontière française' },
        { file: 'photos/jour-01/08.jpg', km: 18.0, caption: 'Bateau-feu rouge · port de Dunkerque' },
        { file: 'photos/jour-01/09.jpg', km: 19.0, caption: 'Trois-mâts « Duchesse Anne » · beffroi de Dunkerque en fond' },
        { file: 'photos/jour-01/10.jpg', km: 20.0, caption: 'Façade orientaliste des « Bains Dunkerquois »' },
        { file: 'photos/jour-01/11.jpg', km: 24.0, caption: '« Sentier de Belgique » · Coudekerque-Branche' },
        { file: 'photos/jour-01/12.jpg', km: 32.0, caption: 'Tour-clocher et place pavée · approche de Bergues' },
        { file: 'photos/jour-01/13.jpg', km: 32.5, caption: 'Borne D 916 · « Bergues · alt mini 4 m, maxi 22 m »' },
      ],
    },
    { num: 2, from: 'Bergues', to: 'Gravelines', weather: 'mixed', weatherNote: '12 °C, ciel variable, vent 20–25 km/h',
      gpx: 'data/02-bergues-gravelines.gpx',
      photos: [
        { file: 'photos/jour-02/01.jpg', km: 0.1, caption: 'Les Capucins · maison d\u2019hôtes à Bergues (départ)' },
        { file: 'photos/jour-02/02.jpg', km: 0.2, caption: 'Météo de Bergues · 12 °C, ciel variable' },
        { file: 'photos/jour-02/03.jpg', km: 0.5, caption: 'Porte fortifiée de Bergues, drapeau flamand' },
        { file: 'photos/jour-02/07.jpg', km: 0.7, caption: 'Beffroi de Bergues sous un ciel d\u2019ardoise' },
        { file: 'photos/jour-02/04.jpg', km: 6.0, caption: 'Petit pont de pierre sur le ruisseau, saule pleureur' },
        { file: 'photos/jour-02/05.jpg', km: 18.0, caption: 'Canal de Bourbourg · longue ligne de fuite' },
        { file: 'photos/jour-02/06.jpg', km: 22.0, caption: 'Sandwich mérité · jambon, fromage, tomate, salade' },
      ],
    },
    { num: 3, from: 'Gravelines', to: 'Calais', weather: null, gpx: 'data/03-gravelines-calais.gpx',
      photos: [
        { file: 'photos/jour-03/01.jpg', km: 1.0,  caption: 'Phare de Petit-Fort-Philippe · départ du chenal' },
        { file: 'photos/jour-03/02.jpg', km: 3.0,  caption: 'Carrefour du GR 120 · Platier d\u2019Oye / Grand-Fort-Philippe' },
        { file: 'photos/jour-03/03.jpg', km: 8.0,  caption: 'Crapaud commun sur le sentier mouillé' },
        { file: 'photos/jour-03/04.jpg', km: 12.0, caption: 'Estran sans fin · ciel d\u2019orage sur le Platier d\u2019Oye' },
        { file: 'photos/jour-03/05.jpg', km: 22.0, caption: 'Coquelicots au bord de la route' },
        { file: 'photos/jour-03/06.jpg', km: 27.0, caption: 'Phare de Calais à contre-jour' },
        { file: 'photos/jour-03/07.jpg', km: 28.0, caption: '« Baguette Banette / Poolish / Tradition » · boulangerie de Calais' },
      ],
    },
    { num: 4, from: 'Calais', to: 'Boulogne-sur-Mer', weather: null, gpx: 'data/04-calais-boulogne.gpx',
      photos: [
        { file: 'photos/jour-04/01.jpg', km: 0.5,  caption: 'Coucher de soleil sur les cabines blanches · plage de Calais (matin de départ)' },
        { file: 'photos/jour-04/02.jpg', km: 1.0,  caption: 'Hôtel-Restaurant de la Plage · Calais' },
        { file: 'photos/jour-04/03.jpg', km: 1.5,  caption: 'Les Bourgeois de Calais (Rodin) devant le beffroi de l\u2019hôtel de ville' },
        { file: 'photos/jour-04/04.jpg', km: 2.0,  caption: '« Calais La Plage » · sculpture cœur ailé avec distances aux villes du monde' },
        { file: 'photos/jour-04/05.jpg', km: 2.5,  caption: 'Cabine de plage en cadre · vue encadrée sur la mer' },
        { file: 'photos/jour-04/06.jpg', km: 3.0,  caption: 'Ferry DFDS au large · entre deux cabines' },
        { file: 'photos/jour-04/07.jpg', km: 10.0, caption: 'Vers le Cap Blanc-Nez · sentier sur la falaise crayeuse' },
        { file: 'photos/jour-04/08.jpg', km: 14.0, caption: 'Phare du Cap Blanc-Nez vu depuis les champs' },
        { file: 'photos/jour-04/09.jpg', km: 19.0, caption: 'Pavot de Californie (eschscholzia) sur le sentier' },
        { file: 'photos/jour-04/10.jpg', km: 22.0, caption: 'Plage de Wissant · dunes de la Côte d\u2019Opale' },
        { file: 'photos/jour-04/11.jpg', km: 28.0, caption: 'Armérie maritime en pleine floraison · falaises du Cap Gris-Nez' },
        { file: 'photos/jour-04/12.jpg', km: 28.5, caption: 'Estran rocheux sous les falaises · armérie en bordure' },
        { file: 'photos/jour-04/13.jpg', km: 33.0, caption: 'Audresselles · maisons au-dessus de l\u2019estran rocheux' },
        { file: 'photos/jour-04/14.jpg', km: 36.0, caption: 'Fort d\u2019Ambleteuse (Vauban) face à la Manche' },
        { file: 'photos/jour-04/15.jpg', km: 38.0, caption: 'Passerelle en bois à travers les dunes boisées' },
        { file: 'photos/jour-04/16.jpg', km: 44.0, caption: 'Villas Belle Époque colorées · digue de Wimereux' },
      ],
    },
    { num: 5, from: 'Boulogne-sur-Mer', to: 'Le Touquet', weather: null, gpx: 'data/05-boulogne-le-touquet.gpx',
      photos: [
        { file: 'photos/jour-05/01.jpg', km: 0.1,  caption: '21 rue Saint-Jean · « La main à la pâte » · départ Boulogne' },
        { file: 'photos/jour-05/03.jpg', km: 0.4,  caption: 'Beffroi de Boulogne sous les pavoisements' },
        { file: 'photos/jour-05/02.jpg', km: 0.6,  caption: 'Goéland argenté · ville haute de Boulogne' },
        { file: 'photos/jour-05/04.jpg', km: 4.0,  caption: 'Voilier au loin · vue de la digue' },
        { file: 'photos/jour-05/05.jpg', km: 6.0,  caption: 'Phare d\u2019Alprech à contre-jour · Le Portel' },
        { file: 'photos/jour-05/06.jpg', km: 14.0, caption: 'Cabines bleues et blanches · Hardelot' },
        { file: 'photos/jour-05/07.jpg', km: 22.0, caption: '« Strictement interdit de tirer en direction des maisons » · panneau cocasse' },
        { file: 'photos/jour-05/08.jpg', km: 28.0, caption: 'Statue de bronze (le voyageur déchiré) · approche d\u2019Étaples' },
      ],
    },
    { num: 6, from: 'Le Touquet', to: 'Fort-Mahon-Plage', weather: null, gpx: 'data/06-le-touquet-fort-mahon.gpx',
      photos: [
        { file: 'photos/jour-06/01.jpg', km: 0.1,  caption: '« Bienvenue à Le Touquet Paris-Plage » · départ' },
        { file: 'photos/jour-06/02.jpg', km: 0.5,  caption: 'Avenue du Bois · chambres d\u2019hôtes' },
        { file: 'photos/jour-06/03.jpg', km: 1.0,  caption: 'Drapeaux européens face à la plage' },
        { file: 'photos/jour-06/04.jpg', km: 2.0,  caption: 'Cabines blanches face à l\u2019estran' },
        { file: 'photos/jour-06/05.jpg', km: 3.5,  caption: 'Ombre du randonneur sur le sable' },
        { file: 'photos/jour-06/06.jpg', km: 5.0,  caption: 'Coquillages sur la plage' },
        { file: 'photos/jour-06/07.jpg', km: 8.0,  caption: 'Mise à l\u2019eau des chars à voile · tracteur sur l\u2019estran' },
        { file: 'photos/jour-06/08.jpg', km: 8.3,  caption: 'Alignement de chars à voile « Seagull »' },
        { file: 'photos/jour-06/09.jpg', km: 8.6,  caption: 'Char à voile vert et bleu · mouette en figure' },
        { file: 'photos/jour-06/10.jpg', km: 11.0, caption: 'Régate sur l\u2019estran de Berck' },
        { file: 'photos/jour-06/11.jpg', km: 11.5, caption: 'Voiles jaunes et orange en ligne' },
        { file: 'photos/jour-06/12.jpg', km: 12.5, caption: '#BERCK SUR MER · grandes lettres sur le sable' },
        { file: 'photos/jour-06/13.jpg', km: 16.0, caption: 'Aubépine blanche en pleine floraison' },
        { file: 'photos/jour-06/14.jpg', km: 19.0, caption: 'Iris des marais (Iris pseudacorus)' },
        { file: 'photos/jour-06/15.jpg', km: 22.0, caption: 'L\u2019Authie · franchissement vers la Somme' },
        { file: 'photos/jour-06/16.jpg', km: 30.0, caption: 'Chaussures de marche au retour à l\u2019hôtel' },
      ],
    },
    { num: 7, from: 'Fort-Mahon-Plage', to: 'Saint-Valéry-sur-Somme', weather: null, gpx: 'data/07-fort-mahon-st-valery.gpx',
      photos: [
        { file: 'photos/jour-07/01.jpg', km: 1.0,  caption: 'Plage et dunes au départ de Fort-Mahon' },
        { file: 'photos/jour-07/02.jpg', km: 3.0,  caption: '« Warning · Gravelots en danger » — réserve de nidification' },
        { file: 'photos/jour-07/03.jpg', km: 5.0,  caption: 'Plume blanche posée dans le sable' },
        { file: 'photos/jour-07/04.jpg', km: 7.0,  caption: 'Empreintes vers la mer' },
        { file: 'photos/jour-07/05.jpg', km: 9.0,  caption: 'Dunes du Marquenterre sous un ciel chargé' },
        { file: 'photos/jour-07/06.jpg', km: 12.0, caption: 'Sentier bitumé à travers les prairies' },
        { file: 'photos/jour-07/07.jpg', km: 15.0, caption: 'Ciel strié au-dessus des polders' },
        { file: 'photos/jour-07/08.jpg', km: 22.0, caption: '« Au Vent du Large » · entrée du Crotoy' },
        { file: 'photos/jour-07/09.jpg', km: 23.0, caption: 'Tourelle Belle Époque · Le Crotoy' },
        { file: 'photos/jour-07/10.jpg', km: 24.0, caption: 'Hôtel Les Tourelles · Le Crotoy' },
        { file: 'photos/jour-07/11.jpg', km: 25.0, caption: 'Hôtel La Terrasse · Le Homard Gourmand · Le Crotoy' },
        { file: 'photos/jour-07/12.jpg', km: 34.0, caption: '« Pivoine & Giroflée » · maison rose au bord de la Somme' },
        { file: 'photos/jour-07/13.jpg', km: 35.5, caption: 'Cabane de chasse de l\u2019autre côté du chenal' },
        { file: 'photos/jour-07/14.jpg', km: 37.0, caption: 'Façade « La Baie de Somme » · Saint-Valéry, vieille ville' },
        { file: 'photos/jour-07/15.jpg', km: 38.5, caption: 'Panneau d\u2019entrée · Saint-Valéry-sur-Somme' },
      ],
    },
    {
      num: 8,
      from: 'Saint-Valéry-sur-Somme',
      to: 'Le Tréport',
      weather: 'sun',
      weatherNote: 'Soleil, ciel dégagé',
      // The original upload uses combining-diacritic file names; we keep the literal
      // ref because the project sandbox can't rewrite those file names.
      gpx: 'data/08-st-valery-le-treport.gpx',
      photos: [
        { file: 'photos/jour-08/06.jpg', km: 0.0,  caption: 'Hôtel La Colonne de Bronze · Saint-Valéry-sur-Somme' },
        { file: 'photos/jour-08/07.jpg', km: 0.2,  caption: 'Plaque de cocher G.C. n°204 vers Le Hourdel' },
        { file: 'photos/jour-08/08.jpg', km: 0.4,  caption: 'Vélos rouges sur le quai' },
        { file: 'photos/jour-08/09.jpg', km: 0.6,  caption: 'Feu vert du port · vue sur la Baie de Somme' },
        { file: 'photos/jour-08/10.jpg', km: 8.0,  caption: 'Cabines face à la baie · Le Hourdel' },
        { file: 'photos/jour-08/11.jpg', km: 8.2,  caption: 'Phare du Hourdel' },
        { file: 'photos/jour-08/12.jpg', km: 13.0, caption: 'Phare de Cayeux-sur-Mer' },
        { file: 'photos/jour-08/13.jpg', km: 13.5, caption: 'L\u2019alignement des cabines · Cayeux-sur-Mer' },
        { file: 'photos/jour-08/14.jpg', km: 14.0, caption: 'Cabines de Cayeux, premier plan' },
        { file: 'photos/jour-08/15.jpg', km: 14.5, caption: 'Cabine orange à l\u2019ancre · Cayeux' },
        { file: 'photos/jour-08/16.jpg', km: 16.0, caption: '« Naturisme autorisé · 1 km sur l\u2019estran » · Hâble d\u2019Ault' },
        { file: 'photos/jour-08/17.jpg', km: 19.0, caption: 'Champ de lin en fleur' },
        { file: 'photos/jour-08/18.jpg', km: 22.0, caption: 'Falaises et casino d\u2019Ault' },
        { file: 'photos/jour-08/03.jpg', km: 24.0, caption: 'Montée vers la falaise' },
        { file: 'photos/jour-08/19.jpg', km: 25.0, caption: 'Troupeau de laitières en pâture' },
        { file: 'photos/jour-08/20.jpg', km: 27.0, caption: 'Falaises blanches · Bois-de-Cise' },
        { file: 'photos/jour-08/02.jpg', km: 28.0, caption: 'Échalier du sentier du littoral' },
        { file: 'photos/jour-08/01.jpg', km: 33.5, caption: 'Villas Belle Époque · Mers-les-Bains' },
        { file: 'photos/jour-08/04.jpg', km: 34.2, caption: 'Francillon & L\u2019Aiglon · Mers-les-Bains' },
        { file: 'photos/jour-08/05.jpg', km: 34.7, caption: 'Villa Clair de Lune · Mers-les-Bains' },
      ],
    },
    { num: 9, from: 'Le Tréport', to: 'Dieppe', weather: null, gpx: 'data/09-le-treport-dieppe.gpx',
      photos: [
        { file: 'photos/jour-09/01.jpg', km: 0.1,  caption: 'Hôtel Le Saint-Yves · départ au Tréport' },
        { file: 'photos/jour-09/02.jpg', km: 0.4,  caption: 'Vue arrière sur Mers-les-Bains depuis la jetée' },
        { file: 'photos/jour-09/04.jpg', km: 0.5,  caption: 'Phare vert de la jetée du Tréport' },
        { file: 'photos/jour-09/06.jpg', km: 0.5,  caption: 'Phare vert · contre-plongée' },
        { file: 'photos/jour-09/03.jpg', km: 0.6,  caption: 'Galets et écume au pied de la digue' },
        { file: 'photos/jour-09/05.jpg', km: 0.8,  caption: 'Plage du Tréport, falaises blanches en fond' },
        { file: 'photos/jour-09/08.jpg', km: 1.0,  caption: 'Drapeau normand sur la tour de l\u2019horloge' },
        { file: 'photos/jour-09/07.jpg', km: 1.3,  caption: '« Escaliers des Falaises » · accès au GR 21' },
        { file: 'photos/jour-09/09.jpg', km: 1.4,  caption: '« Je les aime bien les n\u2019importe quoi » · Graf Flower' },
        { file: 'photos/jour-09/10.jpg', km: 1.6,  caption: 'Montée des escaliers vers la falaise' },
        { file: 'photos/jour-09/11.jpg', km: 5.0,  caption: 'Poteau directionnel · Paris 150, Bruxelles 230, Hastings 105' },
        { file: 'photos/jour-09/12.jpg', km: 8.0,  caption: '« Présence de randonneurs » · route des falaises' },
        { file: 'photos/jour-09/13.jpg', km: 12.0, caption: 'Cabines de plage colorées sous la falaise · Criel-sur-Mer' },
        { file: 'photos/jour-09/14.jpg', km: 16.0, caption: 'Bourrache en fleur sur le sentier' },
        { file: 'photos/jour-09/15.jpg', km: 19.0, caption: 'Boule de neige (viorne obier) blanche' },
        { file: 'photos/jour-09/16.jpg', km: 22.0, caption: 'Aubépine rose en pleine floraison' },
        { file: 'photos/jour-09/17.jpg', km: 30.0, caption: 'Ciel d\u2019orage sur les falaises · approche de Dieppe' },
        { file: 'photos/jour-09/18.jpg', km: 36.5, caption: 'Chalutiers à quai · « L\u2019Avenir Dieppe » · port de Dieppe' },
      ],
    },
    { num: 10, from: 'Dieppe', to: 'Veules-les-Roses', weather: null, gpx: 'data/10-dieppe-veules-les-roses.gpx',
      photos: [
        { file: 'photos/jour-10/01.jpg', km: 0.1,  caption: 'Hôtel Grand Duquesne · rue de Sygogne, Dieppe (départ)' },
        { file: 'photos/jour-10/02.jpg', km: 0.2,  caption: 'Street art « Sens interdit · pêcheur » de Clet · rue de Dieppe' },
        { file: 'photos/jour-10/03.jpg', km: 0.4,  caption: 'Street art « Sens interdit · porteur de barre » de Clet · centre Dieppe' },
        { file: 'photos/jour-10/04.jpg', km: 0.7,  caption: 'Mur de brique fleuri · érigéron de Karvinsky et campanule des murs' },
        { file: 'photos/jour-10/05.jpg', km: 1.5,  caption: 'Drapeau normand (lions léopardés) sous ciel bleu · ville haute de Dieppe' },
        { file: 'photos/jour-10/06.jpg', km: 2.5,  caption: 'Falaises ouest de Dieppe · ciel d\u2019orage et mer agitée' },
        { file: 'photos/jour-10/07.jpg', km: 4.0,  caption: 'Villa Belle Époque en brique polychrome · Pourville-sur-Mer' },
        { file: 'photos/jour-10/08.jpg', km: 5.0,  caption: 'Panneau « GR 21 · La Mer · La Terre » peint à la main' },
        { file: 'photos/jour-10/09.jpg', km: 5.5,  caption: 'Cabines pastel alignées face à la mer · Pourville' },
        { file: 'photos/jour-10/10.jpg', km: 6.0,  caption: 'Drapeaux orange et noir de pêcheurs (DP 929 608 · Jourdan) sur le port' },
        { file: 'photos/jour-10/11.jpg', km: 8.0,  caption: 'Deux arbres tordus par le vent · vue sur la Manche' },
        { file: 'photos/jour-10/12.jpg', km: 9.5,  caption: 'Phare d\u2019Ailly · Sainte-Marguerite-sur-Mer (dôme vert)' },
        { file: 'photos/jour-10/13.jpg', km: 11.0, caption: 'Longue maison à colombages normande · ferme du Vasterival' },
        { file: 'photos/jour-10/14.jpg', km: 12.0, caption: 'Manoir anglo-normand jaune et noir · Sainte-Marguerite' },
        { file: 'photos/jour-10/15.jpg', km: 14.0, caption: 'Compagnons rouges (Silene dioica) en bord de sentier' },
        { file: 'photos/jour-10/16.jpg', km: 16.0, caption: 'Panneau métallique « LA MER » · indication de hameau' },
        { file: 'photos/jour-10/17.jpg', km: 19.0, caption: 'Balisage GR jaune-blanc-rouge sur piquet · Quiberville en vue' },
        { file: 'photos/jour-10/18.jpg', km: 22.0, caption: 'Anthémis des teinturiers (marguerites dorées) sur le talus' },
        { file: 'photos/jour-10/19.jpg', km: 25.0, caption: 'Sentier sous branche d\u2019arbre · échappée sur la Manche' },
        { file: 'photos/jour-10/20.jpg', km: 28.0, caption: 'Vue plongeante sur les falaises et la plage · approche de Veules-les-Roses' },
      ],
    },
    { num: 11, from: 'Veules-les-Roses', to: 'Saint-Pierre-en-Port', weather: null, gpx: 'data/11-veules-les-roses-st-pierre-en-port.gpx',
      photos: [
        { file: 'photos/jour-11/06.jpg', km: 0.1,  caption: 'Place des Écossais · maison brique et silex, Veules-les-Roses (départ)' },
        { file: 'photos/jour-11/18.jpg', km: 0.3,  caption: 'Roses pâles · Veules-les-Roses, le village qui porte leur nom' },
        { file: 'photos/jour-11/25.jpg', km: 0.5,  caption: 'Rose fuchsia · seconde halte au jardin' },
        { file: 'photos/jour-11/20.jpg', km: 0.8,  caption: 'Panneau « Rue du Paradis » · sortie de Veules' },
        { file: 'photos/jour-11/05.jpg', km: 3.0,  caption: 'Plaque émaillée « Sente des Douaniers » · sur le GR 21' },
        { file: 'photos/jour-11/01.jpg', km: 5.5,  caption: 'Pont levant vert · Port de Saint-Valéry-en-Caux' },
        { file: 'photos/jour-11/02.jpg', km: 5.8,  caption: '« Ici vécut de 1968 à 1993 · Pierre Bérégovoy · Premier ministre »' },
        { file: 'photos/jour-11/03.jpg', km: 6.0,  caption: 'Goéland argenté sur fronton de brique · Saint-Valéry-en-Caux' },
        { file: 'photos/jour-11/04.jpg', km: 8.0,  caption: 'Champs verts surplombant la Manche · plateau cauchois' },
        { file: 'photos/jour-11/21.jpg', km: 11.0, caption: 'Voilier isolé au large · vu depuis un champ vert' },
        { file: 'photos/jour-11/13.jpg', km: 13.0, caption: 'Vue plongeante sur Veulettes-sur-Mer · cabines alignées et galets' },
        { file: 'photos/jour-11/14.jpg', km: 13.2, caption: 'Veulettes-sur-Mer · piscine et aire de jeux, falaise en fond' },
        { file: 'photos/jour-11/12.jpg', km: 13.5, caption: 'Phare de Veulettes-sur-Mer · vue depuis la digue' },
        { file: 'photos/jour-11/27.jpg', km: 13.8, caption: 'Phare de Veulettes · sur la jetée pavée' },
        { file: 'photos/jour-11/15.jpg', km: 14.3, caption: 'Cabines bleues et blanches imbriquées · « JiNIMI »' },
        { file: 'photos/jour-11/16.jpg', km: 14.5, caption: 'Façades Belle Époque à balcons de bois · Veulettes' },
        { file: 'photos/jour-11/11.jpg', km: 16.0, caption: 'Longère normande à colombages et toit de chaume' },
        { file: 'photos/jour-11/26.jpg', km: 17.0, caption: 'Arbre tordu par le vent · clôture du plateau' },
        { file: 'photos/jour-11/22.jpg', km: 18.0, caption: 'Pavots de Californie orange · talus en fleurs' },
        { file: 'photos/jour-11/09.jpg', km: 19.0, caption: 'Pigeon perché · éolienne du plateau cauchois en fond' },
        { file: 'photos/jour-11/10.jpg', km: 19.5, caption: 'Éolienne en contre-plongée · ciel cirreux' },
        { file: 'photos/jour-11/08.jpg', km: 20.0, caption: 'Parapente vert au-dessus de la mer · parc éolien de Fécamp à l\u2019horizon' },
        { file: 'photos/jour-11/07.jpg', km: 24.0, caption: 'Falaises blanches verticales · plage de galets' },
        { file: 'photos/jour-11/24.jpg', km: 24.3, caption: 'Galets ronds et falaises grises sous éclaircie d\u2019orage' },
        { file: 'photos/jour-11/17.jpg', km: 24.5, caption: 'Cap rocheux brun · estran sombre à marée basse' },
        { file: 'photos/jour-11/19.jpg', km: 25.0, caption: 'Vue plongeante sur falaise brune et hameau de pied · Les Petites Dalles' },
        { file: 'photos/jour-11/23.jpg', km: 25.5, caption: 'Falaise + plage de galets + parking · Les Grandes Dalles' },
        { file: 'photos/jour-11/28.jpg', km: 26.5, caption: 'Vue plongeante sur l\u2019estran et la plage · arrivée à Saint-Pierre-en-Port' },
      ],
    },
    { num: 12, from: 'Saint-Pierre-en-Port', to: 'Étretat', weather: null, gpx: 'data/12-st-pierre-en-port-etretat.gpx',
      photos: [
        { file: 'photos/jour-12/01.jpg', km: 0.5,  caption: 'Falaise crayeuse + parc éolien de Fécamp à l\u2019horizon · départ Saint-Pierre-en-Port' },
        { file: 'photos/jour-12/03.jpg', km: 3.0,  caption: 'Cheval noir au pré · arrêt cajôleries' },
        { file: 'photos/jour-12/02.jpg', km: 5.0,  caption: 'Rhododendrons roses en pleine floraison' },
        { file: 'photos/jour-12/13.jpg', km: 8.0,  caption: 'Falaise verte plongeant dans le bleu · sentier au sommet' },
        { file: 'photos/jour-12/04.jpg', km: 12.0, caption: 'Fécamp vu d\u2019en haut · port, ville et falaises de la Vierge' },
        { file: 'photos/jour-12/05.jpg', km: 13.0, caption: 'Port de Fécamp · voiliers à quai sous ciel bleu' },
        { file: 'photos/jour-12/08.jpg', km: 13.2, caption: 'Vieux gréement à coque bleue · port de Fécamp' },
        { file: 'photos/jour-12/06.jpg', km: 13.5, caption: 'Étal du poissonnier · raies, tacauds, grondins · Fécamp' },
        { file: 'photos/jour-12/07.jpg', km: 13.8, caption: 'Pause torsade au chocolat & café Richard · Fécamp' },
        { file: 'photos/jour-12/09.jpg', km: 15.0, caption: 'Galets ronds gris · plage de Fécamp ou Yport' },
        { file: 'photos/jour-12/10.jpg', km: 22.0, caption: 'Cabines rayées noir et blanc · plage d\u2019Yport, falaise verte en fond' },
        { file: 'photos/jour-12/11.jpg', km: 25.0, caption: 'Falaises de craie + estran sombre · eau turquoise' },
        { file: 'photos/jour-12/12.jpg', km: 27.0, caption: 'Passage taillé entre deux pans de falaise · accès plage' },
        { file: 'photos/jour-12/14.jpg', km: 30.0, caption: 'Aiguille isolée au pied de la falaise · approche d\u2019Étretat' },
        { file: 'photos/jour-12/15.jpg', km: 31.0, caption: 'Aiguille de craie verticale · gros plan' },
        { file: 'photos/jour-12/16.jpg', km: 32.0, caption: 'Enfilade de falaises · vue sur la Côte d\u2019Albâtre' },
        { file: 'photos/jour-12/19.jpg', km: 33.0, caption: 'Plage d\u2019Étretat & Porte d\u2019Aval · vue d\u2019ensemble' },
        { file: 'photos/jour-12/17.jpg', km: 33.2, caption: 'Porte d\u2019Aval & Aiguille d\u2019Étretat · plage de galets' },
        { file: 'photos/jour-12/18.jpg', km: 33.5, caption: 'Arche de la Porte d\u2019Aval & l\u2019Aiguille' },
        { file: 'photos/jour-12/20.jpg', km: 33.8, caption: 'Porte d\u2019Aval & cerfs-volants colorés en vol' },
        { file: 'photos/jour-12/21.jpg', km: 34.5, caption: '« Maisons des illustres · Maurice Leblanc 1864-1941 » · Étretat' },
        { file: 'photos/jour-12/22.jpg', km: 34.6, caption: 'Le Clos Lupin · villa de Maurice Leblanc, père d\u2019Arsène Lupin' },
      ],
    },
    { num: 13, from: 'Étretat', to: 'Le Havre', weather: null, gpx: 'data/13-etretat-le-havre.gpx',
      photos: [
        { file: 'photos/jour-13/01.jpg', km: 0.1,  caption: 'Manoir de la Salamandre · Hôtel La Résidence, Étretat (départ)' },
        { file: 'photos/jour-13/03.jpg', km: 0.4,  caption: 'Goéland argenté sur les kayaks · plage d\u2019Étretat' },
        { file: 'photos/jour-13/04.jpg', km: 0.5,  caption: 'Kayaks colorés alignés face à la Porte d\u2019Aval' },
        { file: 'photos/jour-13/02.jpg', km: 0.8,  caption: 'Porte d\u2019Aval & Aiguille · plage de galets sous ciel gris' },
        { file: 'photos/jour-13/05.jpg', km: 2.5,  caption: 'L\u2019Aiguille & l\u2019Arche · vue plongeante depuis la falaise sud' },
        { file: 'photos/jour-13/06.jpg', km: 3.5,  caption: 'Falaises sud d\u2019Étretat · vers la Manneporte' },
        { file: 'photos/jour-13/07.jpg', km: 5.0,  caption: 'Brin d\u2019herbe perlé de pluie & mouche · sentier après l\u2019averse' },
        { file: 'photos/jour-13/08.jpg', km: 6.0,  caption: 'Iris violet ruisselant · jardin de hameau' },
        { file: 'photos/jour-13/09.jpg', km: 8.0,  caption: 'Panneau « Chemin des Écoliers » & balise GR' },
        { file: 'photos/jour-13/10.jpg', km: 12.0, caption: 'Vache normande noir & blanc et son veau pie-rouge · pays de Caux' },
        { file: 'photos/jour-13/11.jpg', km: 13.0, caption: 'Vaches normandes en pâture · robe pie-rouge' },
        { file: 'photos/jour-13/12.jpg', km: 14.0, caption: 'Une autre rencontre bovine sur le plateau' },
        { file: 'photos/jour-13/13.jpg', km: 16.0, caption: 'Panneau « Chemin des Sangliers » · ambiance plateau boisé' },
        { file: 'photos/jour-13/14.jpg', km: 25.0, caption: '« Maison fond » de Leandro Erlich · illusion d\u2019optique, Le Havre' },
        { file: 'photos/jour-13/15.jpg', km: 25.1, caption: '« Maison fond » vue de face · n°79, Le Havre (arrivée)' },
      ],
    },
    { num: 14, from: 'Honfleur', to: 'Blonville-sur-Mer', weather: null, gpx: 'data/14-honfleur-blonville.gpx',
      photos: [
        { file: 'photos/jour-14/06.jpg', km: 0.1,  caption: '« Claire · 58 » · plaque de rue et lettres en laiton, Honfleur (départ)' },
        { file: 'photos/jour-14/21.jpg', km: 0.5,  caption: 'Chapelle Notre-Dame-de-Grâce · Côte de Grâce, Honfleur' },
        { file: 'photos/jour-14/22.jpg', km: 0.8,  caption: 'Panneau C4 · « Trouville par la Côte de Grâce »' },
        { file: 'photos/jour-14/18.jpg', km: 2.0,  caption: 'Street art « Totoro au cœur étincelant » · sortie d\u2019Honfleur' },
        { file: 'photos/jour-14/19.jpg', km: 6.0,  caption: 'Manoir normand à colombages bicolores · plateau au-dessus de la Manche' },
        { file: 'photos/jour-14/16.jpg', km: 9.0,  caption: 'Passerelle en bois sur un ruisseau · sentier ombragé' },
        { file: 'photos/jour-14/17.jpg', km: 12.0, caption: 'Sous-bois en fleurs · rhododendrons violets le long du chemin' },
        { file: 'photos/jour-14/20.jpg', km: 14.0, caption: 'Vache normande limousine et son veau au pis · troupeau en pâture' },
        { file: 'photos/jour-14/03.jpg', km: 18.0, caption: 'Manche de vent rouge & blanche · gonflée au-dessus de la Manche' },
        { file: 'photos/jour-14/13.jpg', km: 20.2, caption: 'Phares jumeaux noir et blanc & pont-levis levé · port de Deauville-Trouville' },
        { file: 'photos/jour-14/14.jpg', km: 20.5, caption: 'Jetée en bois & feu rouge · sortie du port de Trouville' },
        { file: 'photos/jour-14/02.jpg', km: 20.8, caption: 'Selfie reflété dans une vitrine · le marcheur en sac rouge devant la mer' },
        { file: 'photos/jour-14/10.jpg', km: 22.0, caption: 'Cabines turquoise « Les Planches » · noms de réalisateurs (Steven Soderbergh, Maurice Jarre…)' },
        { file: 'photos/jour-14/07.jpg', km: 22.2, caption: 'Les Planches de Deauville · Thandiwe Newton, F.F. Coppola, Jesse Eisenberg…' },
        { file: 'photos/jour-14/15.jpg', km: 22.5, caption: 'Villa Belle Époque à colombages vert sauge · front de mer Deauville' },
        { file: 'photos/jour-14/04.jpg', km: 22.8, caption: 'Villa à tourelle pointue · stations balnéaires Belle Époque' },
        { file: 'photos/jour-14/08.jpg', km: 23.0, caption: 'Poste de secours « Deauville » · plage déserte sous ciel gris' },
        { file: 'photos/jour-14/09.jpg', km: 23.2, caption: 'Transats bleus et rouges « Bar de la Mer » · Deauville' },
        { file: 'photos/jour-14/05.jpg', km: 25.0, caption: 'Plage et planches en bois · Bénerville-sur-Mer' },
        { file: 'photos/jour-14/11.jpg', km: 28.0, caption: 'Poteau en bois & balisage GR rouge-blanc · plage à marée basse' },
        { file: 'photos/jour-14/01.jpg', km: 30.0, caption: 'Pieux en bois et galets · arrivée à Blonville-sur-Mer' },
      ],
    },
    { num: 15, from: 'Blonville-sur-Mer', to: 'Ouistreham', weather: null, gpx: 'data/15-blonville-ouistreham.gpx',
      photos: [
        { file: 'photos/jour-15/17.jpg', km: 0.0,  caption: 'Selfie miroir · veste bleue et sac à dos, prêt à partir' },
        { file: 'photos/jour-15/14.jpg', km: 2.0,  caption: 'Villa rouge à tuiles écailles & rosiers grimpants · Villers-sur-Mer' },
        { file: 'photos/jour-15/02.jpg', km: 3.0,  caption: 'Lotier corniculé en pleine floraison · talus jaune' },
        { file: 'photos/jour-15/16.jpg', km: 4.0,  caption: 'Plage et marée basse · ciel pommelé sur Houlgate' },
        { file: 'photos/jour-15/03.jpg', km: 5.5,  caption: 'Bois flottés blanchis dans le sable · plage' },
        { file: 'photos/jour-15/04.jpg', km: 6.0,  caption: 'Tapis de coquillages · plage de Houlgate' },
        { file: 'photos/jour-15/07.jpg', km: 8.0,  caption: 'Port de plaisance de Dives-Cabourg · voiliers à quai' },
        { file: 'photos/jour-15/01.jpg', km: 8.3,  caption: 'Mât du fileyeur « Trémit » et perches à fanions verts du port de Dives' },
        { file: 'photos/jour-15/12.jpg', km: 14.0, caption: 'Sentier le long du chenal · épave de barque rongée' },
        { file: 'photos/jour-15/05.jpg', km: 17.0, caption: '« Land Art » · cube de bois suspendu et fagot de branchages · estuaire de l\u2019Orne' },
        { file: 'photos/jour-15/08.jpg', km: 19.0, caption: 'Borne GR rouge-blanc sous bois · sentier ombragé' },
        { file: 'photos/jour-15/13.jpg', km: 22.0, caption: '« Merville-Franceville-Plage » · fronton à colombages, drapeaux UK & FR' },
        { file: 'photos/jour-15/18.jpg', km: 22.5, caption: 'Vestes US Airborne, béret rouge para & casque d\u2019acier · mémorial du Débarquement' },
        { file: 'photos/jour-15/11.jpg', km: 23.0, caption: 'Canon antiaérien Bofors 40 mm · place de Merville-Franceville' },
        { file: 'photos/jour-15/10.jpg', km: 24.5, caption: '« Site Pegasus Bridge · Le Pont de la Paix entre les peuples · là où tout a commencé »' },
        { file: 'photos/jour-15/15.jpg', km: 26.0, caption: '« Chez Gaby · épicerie, boisson fraîche, glaces » · pause sur la route' },
        { file: 'photos/jour-15/09.jpg', km: 28.0, caption: 'Rayons de soleil traversant les nuages · plage de Ouistreham (arrivée)' },
      ],
    },
    { num: 16, from: 'Ouistreham', to: 'Arromanches-les-Bains', weather: null, gpx: 'data/16-ouistreham-arromanches.gpx',
      photos: [
        { file: 'photos/jour-16/13.jpg', km: 0.5,  caption: 'Chaussettes de marche à sécher sur le banc · pause au départ' },
        { file: 'photos/jour-16/11.jpg', km: 0.8,  caption: 'Sculpture en acier corten « Canal de Caen à la mer » · phare en fond' },
        { file: 'photos/jour-16/04.jpg', km: 3.0,  caption: 'Étal du poissonnier · bars sauvages, lottes, turbots' },
        { file: 'photos/jour-16/03.jpg', km: 3.2,  caption: 'Étal au marché · filets de merlan, bars sauvages, salmonelle' },
        { file: 'photos/jour-16/15.jpg', km: 4.0,  caption: 'Bouledogue anglais sur le trottoir · rencontre matinale' },
        { file: 'photos/jour-16/06.jpg', km: 5.0,  caption: 'Pieux moussus verts plantés dans le sable · brise-lames à marée basse' },
        { file: 'photos/jour-16/07.jpg', km: 7.0,  caption: 'Drapeaux des Alliés : UK, Pologne, Pays-Bas, Norvège, USA, Canada, Belgique, Danemark · D-Day' },
        { file: 'photos/jour-16/08.jpg', km: 9.0,  caption: 'Cabines colorées blanche, jaune & orange face à l\u2019estran à marée basse' },
        { file: 'photos/jour-16/09.jpg', km: 12.0, caption: 'Passerelle en bois & poste de secours blanc face à la mer' },
        { file: 'photos/jour-16/10.jpg', km: 16.0, caption: 'Trois villas Belle Époque à colombages rouge & bleu · front de mer normand' },
        { file: 'photos/jour-16/05.jpg', km: 20.0, caption: 'Pieux en bois moussus en file vers la mer · marée basse' },
        { file: 'photos/jour-16/14.jpg', km: 22.0, caption: 'Hôtel-Brasserie « Le Phare » · pause sur la route' },
        { file: 'photos/jour-16/02.jpg', km: 28.0, caption: 'Croix de Lorraine monumentale face à la mer · mémorial du Débarquement' },
        { file: 'photos/jour-16/01.jpg', km: 30.0, caption: '« Standing with Giants » · silhouettes de soldats dans les coquelicots & bleuets, Ver-sur-Mer (Gold Beach)' },
      ],
    },
    { num: 17, from: 'Arromanches-les-Bains', to: 'Saint-Laurent-sur-Mer', weather: null, gpx: 'data/17-arromanches-st-laurent.gpx',
      photos: [
        { file: 'photos/jour-17/05.jpg', km: 0.0,  caption: 'Sac à dos, chapeau, gourde et topo-guide « Côte d\u2019Albâtre / Falaises du Bessin » · départ Arromanches' },
        { file: 'photos/jour-17/13.jpg', km: 0.3,  caption: 'Drapeaux des Alliés au-dessus du Mulberry · Arromanches' },
        { file: 'photos/jour-17/10.jpg', km: 0.5,  caption: 'Vue plongeante sur Arromanches & les caissons du port artificiel · marée basse' },
        { file: 'photos/jour-17/14.jpg', km: 0.7,  caption: 'Caisson Phoenix échoué sur la plage · port artificiel d\u2019Arromanches' },
        { file: 'photos/jour-17/11.jpg', km: 0.9,  caption: 'Caissons Mulberry au large vus depuis le sentier' },
        { file: 'photos/jour-17/12.jpg', km: 1.5,  caption: '« Le Mulberry » · restaurant Les P\u2019tites Assiettes, façade en pierre' },
        { file: 'photos/jour-17/06.jpg', km: 3.0,  caption: 'Chapelle Sainte-Marie en ruines (clocher complet) · falaise sur la mer' },
        { file: 'photos/jour-17/07.jpg', km: 3.1,  caption: 'Clocher des ruines · contre-plongée, ciel bleu profond' },
        { file: 'photos/jour-17/15.jpg', km: 6.0,  caption: 'Batterie allemande de Longues-sur-Mer · canon 150 mm dans son bunker' },
        { file: 'photos/jour-17/09.jpg', km: 9.0,  caption: 'Champ de marguerites face à la mer · vue sur Port-en-Bessin' },
        { file: 'photos/jour-17/08.jpg', km: 13.0, caption: 'Panneau « Sentier littoral · accès interdit · éboulement de falaise » (arrêté de 2001)' },
        { file: 'photos/jour-17/16.jpg', km: 14.0, caption: 'Panneau « 18 % » · descente raide vers Port-en-Bessin' },
        { file: 'photos/jour-17/04.jpg', km: 18.0, caption: 'Citroën Traction Avant noire (393-CN-14) · ambiance Bessin années 50' },
        { file: 'photos/jour-17/17.jpg', km: 22.0, caption: 'Plaque « 1944 NORMANDY 2019 · Operation Overlord · D-Day 75th Anniversary » (82e & 101e Airborne)' },
        { file: 'photos/jour-17/03.jpg', km: 25.0, caption: 'Monument de la 1re Division d\u2019Infanterie US · obélisque face à la mer, Colleville-sur-Mer' },
        { file: 'photos/jour-17/02.jpg', km: 26.0, caption: '« Espace naturel sensible · Omaha Beach » · Commune de Colleville-sur-Mer' },
        { file: 'photos/jour-17/01.jpg', km: 28.0, caption: '« Les Braves » (Anilore Banon) & panneau historique « Omaha Beach, haut lieu du Débarquement »' },
      ],
    },
    { num: 18, from: 'Saint-Laurent-sur-Mer', to: 'Isigny-sur-Mer', weather: null, gpx: 'data/18-st-laurent-isigny.gpx',
      photos: [
        { file: 'photos/jour-18/13.jpg', km: 0.1,  caption: 'Panneau Omaha Beach · Vierville ←, St-Laurent → · départ' },
        { file: 'photos/jour-18/14.jpg', km: 0.3,  caption: 'Sculpture « Les Braves » d\u2019Anilore Banon · plage déserte au soleil' },
        { file: 'photos/jour-18/12.jpg', km: 0.5,  caption: 'Plage d\u2019Omaha à marée basse · falaises jaunes au fond' },
        { file: 'photos/jour-18/11.jpg', km: 1.0,  caption: 'Combi VW rouge personnalisé (yeux Flash McQueen) · CQ-120-VG' },
        { file: 'photos/jour-18/05.jpg', km: 3.0,  caption: 'Bunker effondré et cailloux blancs · falaises de la Pointe de la Percée' },
        { file: 'photos/jour-18/09.jpg', km: 4.5,  caption: 'Pointe rocheuse et plage de galets · vue plongeante depuis le sentier' },
        { file: 'photos/jour-18/10.jpg', km: 5.0,  caption: 'Falaises calcaires & fleurs sauvages · approche Pointe du Hoc' },
        { file: 'photos/jour-18/04.jpg', km: 8.0,  caption: 'Bouquetins du large · concrétions calcaires émergeant à marée basse' },
        { file: 'photos/jour-18/15.jpg', km: 14.0, caption: 'Citroën DS Palm Beach noire décapotable · 57-KW · rencontre vintage' },
        { file: 'photos/jour-18/01.jpg', km: 17.0, caption: 'Panneau « Gîte et chambre à la ferme à 100 m » · vache stylisée' },
        { file: 'photos/jour-18/03.jpg', km: 20.0, caption: 'Lagures (queues-de-lièvre) au soleil rasant · graminées dorées' },
        { file: 'photos/jour-18/06.jpg', km: 24.0, caption: 'Port-en-Bessin · chalutiers colorés à quai, reflets dans l\u2019eau verte' },
        { file: 'photos/jour-18/08.jpg', km: 28.0, caption: 'Parcs ostréicoles · tables d\u2019huîtres à marée basse, Grandcamp-Maisy' },
        { file: 'photos/jour-18/07.jpg', km: 30.0, caption: 'Plante grasse en fleur (arbre à artichaut) · jardin de hameau' },
        { file: 'photos/jour-18/02.jpg', km: 35.0, caption: 'Camion Citroën Type H · « Laiterie coopérative d\u2019Isigny · Isigny Sainte Mère » (ED-648-EG)' },
        { file: 'photos/jour-18/16.jpg', km: 36.5, caption: 'Sac à dos & chaussures de marche posés · porte ouverte sur le jardin, Isigny (arrivée)' },
      ],
    },
    { num: 19, from: 'Isigny-sur-Mer', to: 'Carentan-les-Marais', weather: null, gpx: 'data/19-isigny-carentan.gpx',
      photos: [
        { file: 'photos/jour-19/13.jpg', km: 0.1,  caption: 'Longue maison de maître en pierre du Bessin · départ d\u2019Isigny-sur-Mer' },
        { file: 'photos/jour-19/07.jpg', km: 0.3,  caption: '« Lait Frais · Produit Fermier » · plaque émaillée vintage' },
        { file: 'photos/jour-19/08.jpg', km: 0.5,  caption: 'Plateau de fromages normands · pont-l\u2019évêque, camembert, livarot, mimolette' },
        { file: 'photos/jour-19/06.jpg', km: 2.0,  caption: 'Flèche peinte « Beurre Super-Isigny · Lanquetot Camemberts » sur mur de maison' },
        { file: 'photos/jour-19/04.jpg', km: 6.0,  caption: 'Ferme en pierre du Bessin pavoisée USA, UK, Canada · mémoire du Débarquement' },
        { file: 'photos/jour-19/12.jpg', km: 9.0,  caption: 'Panneau « département de la Manche » & balise GR 223 sur le poteau' },
        { file: 'photos/jour-19/05.jpg', km: 12.0, caption: 'Canal de Carentan à la mer · ligne droite vers l\u2019horizon, prés-salés' },
        { file: 'photos/jour-19/09.jpg', km: 18.0, caption: '« In memory of · Sgt Pilot Raymond Frederick Charles Dean · 1922-1941 » · drapeaux FR & UK' },
        { file: 'photos/jour-19/03.jpg', km: 22.0, caption: 'Proue de drakkar viking sculptée · port de plaisance de Carentan' },
        { file: 'photos/jour-19/10.jpg', km: 22.3, caption: 'Voiliers et drapeau normand rouge à 3 léopards · port de Carentan' },
        { file: 'photos/jour-19/02.jpg', km: 22.5, caption: 'Mât pavoisé du drapeau normand au-dessus d\u2019un vieux gréement' },
        { file: 'photos/jour-19/11.jpg', km: 23.0, caption: 'Voiliers à quai et drapeau normand · port de plaisance de Carentan' },
        { file: 'photos/jour-19/01.jpg', km: 23.5, caption: '« Carentan · Les Marais » · lettres géantes à l\u2019entrée de la ville (arrivée)' },
      ],
    },
    { num: 20, from: 'Carentan-les-Marais', to: 'Saint-Marcouf-de-l\u2019Isle', weather: null, gpx: 'data/20-carentan-st-marcouf.gpx',
      photos: [
        { file: 'photos/jour-20/12.jpg', km: 0.5,  caption: 'Canal de Carentan au petit matin · alignement d\u2019arbres en contre-jour' },
        { file: 'photos/jour-20/10.jpg', km: 4.0,  caption: 'Roseaux & canal entre marais · réserve naturelle du Cotentin' },
        { file: 'photos/jour-20/06.jpg', km: 9.0,  caption: 'Route littorale & « 1944 D-Day » · signalisation touristique de la Manche' },
        { file: 'photos/jour-20/09.jpg', km: 14.0, caption: '« McGowan Road » · en mémoire du PFC W.F. McGowan, 531st Engr. Shore Regt., tué le 6 juin 1944' },
        { file: 'photos/jour-20/11.jpg', km: 18.0, caption: '« Utah Beach » · piste cyclable Vélomaritime, balise GR rouge & blanche' },
        { file: 'photos/jour-20/08.jpg', km: 19.0, caption: 'Casquette « Normandy D-Day · 6th June 1944 » · drapeaux CAN/UK/FR/USA brodés, boutique de souvenirs' },
        { file: 'photos/jour-20/04.jpg', km: 24.0, caption: 'Coquille Saint-Jacques fraîche échouée sur le sable' },
        { file: 'photos/jour-20/05.jpg', km: 25.0, caption: 'Parcs à huîtres à marée basse · longues lignes de poches sur tables' },
        { file: 'photos/jour-20/07.jpg', km: 25.3, caption: 'Poches d\u2019huîtres noires & vertes · perspective filante vers la mer' },
        { file: 'photos/jour-20/03.jpg', km: 27.5, caption: '« Camping Le Canada *** » · panneau d\u2019entrée face à la mer' },
        { file: 'photos/jour-20/02.jpg', km: 27.7, caption: 'Tipi en bois à toit double-pente · sac à dos posé, arrivée au camping' },
        { file: 'photos/jour-20/01.jpg', km: 27.8, caption: 'Intérieur du tipi · deux lits jumeaux, couettes brunes & oreillers' },
      ],
    },
    { num: 21, from: 'Saint-Marcouf-de-l’Isle', to: 'Barfleur', weather: null,
      date: '2026-05-26', // 1 jour de repos entre l'étape 20 et l'étape 21
      gpx: 'data/21-st-marcouf-barfleur.gpx',
      photos: [
        { file: 'photos/jour-21/04.jpg', km: 0.5,  caption: 'Plage et estran rocheux face à la Manche · départ de Saint-Marcouf' },
        { file: 'photos/jour-21/12.jpg', km: 1.0,  caption: 'Borne « Sentier Littoral · GR®223 · n°89 · Fontenay-sur-Mer » couverte de lichen' },
        { file: 'photos/jour-21/05.jpg', km: 4.0,  caption: 'Deux bornes en pierre · accès au sentier littoral entre les dunes' },
        { file: 'photos/jour-21/07.jpg', km: 6.0,  caption: '« Risque de projection par fortes marées » · panneau et balise FFRandonnée' },
        { file: 'photos/jour-21/06.jpg', km: 12.0, caption: 'Silhouette de la tour Vauban de Saint-Vaast-la-Hougue à marée basse' },
        { file: 'photos/jour-21/13.jpg', km: 16.0, caption: 'Tonton souriant entre les casiers Orval · pause épicerie' },
        { file: 'photos/jour-21/11.jpg', km: 18.0, caption: 'Lodges-bulles transparentes du camping · hébergement insolite' },
        { file: 'photos/jour-21/10.jpg', km: 18.2, caption: 'Tente-tipi en bois · sac à dos posé à l’entrée' },
        { file: 'photos/jour-21/09.jpg', km: 18.5, caption: 'Façade peinte « Le Canada » · camping de bord de mer' },
        { file: 'photos/jour-21/08.jpg', km: 22.0, caption: 'Goéland argenté perché sur un mât de levage · port de Barfleur' },
        { file: 'photos/jour-21/01.jpg', km: 25.0, caption: 'Phare blanc à toit rouge sur la jetée en pierre · entrée du port de Barfleur' },
        { file: 'photos/jour-21/03.jpg', km: 25.3, caption: 'Chalutiers bleu/rouge alignés le long du quai · clocher en fond' },
        { file: 'photos/jour-21/02.jpg', km: 25.5, caption: 'Petites barques colorées échouées et chalutiers · port à marée basse, Barfleur' },
      ],
    },
    { num: 22, from: 'Barfleur', to: 'Cherbourg', weather: null,
      date: '2026-05-27',
      gpx: 'data/22-barfleur-cherbourg.gpx',
      photos: [
        { file: 'photos/jour-22/05.jpg', km: 0.0,  caption: 'Aube dorée sur le port de Barfleur · clocher fortifié en silhouette · départ' },
        { file: 'photos/jour-22/06.jpg', km: 0.3,  caption: 'Chambres d\u2019hôtes « Le Conquérant » · maison en granit, rues 16-18 · Barfleur' },
        { file: 'photos/jour-22/04.jpg', km: 0.6,  caption: 'Vieux gréements alignés au quai · « CH 517599 », couleurs vives' },
        { file: 'photos/jour-22/03.jpg', km: 0.8,  caption: 'Doris bleu & bateaux traditionnels à quai · marée basse de Barfleur' },
        { file: 'photos/jour-22/02.jpg', km: 1.0,  caption: 'Filets de pêche orange et beige amoncelés sur le quai' },
        { file: 'photos/jour-22/01.jpg', km: 2.0,  caption: 'Doris vert à deux mâts & feu blanc de la jetée · sortie du port' },
        { file: 'photos/jour-22/17.jpg', km: 5.0,  caption: 'Phare de Gatteville et la vieille tour-vigie vus du sentier littoral' },
        { file: 'photos/jour-22/16.jpg', km: 5.5,  caption: 'Phare de Gatteville · 75 m de granit, 2e plus haut phare d\u2019Europe' },
        { file: 'photos/jour-22/10.jpg', km: 12.0, caption: 'Côte rocheuse & sémaphore blanc au loin · pointe du Cotentin' },
        { file: 'photos/jour-22/11.jpg', km: 18.0, caption: 'Pose triomphale bras grands ouverts · t-shirt jaune sur la lande rocheuse 🌞' },
        { file: 'photos/jour-22/12.jpg', km: 18.5, caption: 'Portrait en contre-plongée · chapeau et barbe blanche sous ciel bleu' },
        { file: 'photos/jour-22/15.jpg', km: 24.0, caption: 'Plage sauvage & estran sablonneux · vers Fermanville / Cap Lévi' },
        { file: 'photos/jour-22/13.jpg', km: 26.0, caption: 'Plage de sable, coquillages et ourlet d\u2019écume · soleil de mai' },
        { file: 'photos/jour-22/09.jpg', km: 32.0, caption: 'Plage de Cherbourg · voiles fluo des optimists & fort de l\u2019Île Pelée 🎏' },
        { file: 'photos/jour-22/08.jpg', km: 34.5, caption: '« Le Parapluie de Cherbourg » · boutique & manufacture, parapluie lavande au mur' },
        { file: 'photos/jour-22/07.jpg', km: 35.5, caption: 'Gare de Cherbourg-en-Cotentin · arrivée finale du GR 223 🏁' },
      ],
    },
  ],
};

// Helpers (shared)
window.TREK_UTIL = {
  fmtDateLong(date) {
    const d = new Date(date);
    const days = ['dimanche','lundi','mardi','mercredi','jeudi','vendredi','samedi'];
    const months = ['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'];
    return `${days[d.getDay()]} ${d.getDate()} ${months[d.getMonth()]}`;
  },
  dateForDay(num) {
    // Look for an explicit date override on the day entry first
    const day = window.TREK.days.find((x) => x.num === num);
    if (day && day.date) return new Date(day.date);
    const d = new Date(window.TREK.startDate);
    d.setDate(d.getDate() + (num - 1));
    return d;
  },
  weatherIcon(code) {
    const icons = {
      sun: { glyph: '☀', label: 'Soleil' },
      cloud: { glyph: '☁', label: 'Couvert' },
      mixed: { glyph: '⛅', label: 'Éclaircies' },
      rain: { glyph: '☂', label: 'Pluie' },
      shower: { glyph: '🌦', label: 'Averses' },
      fog: { glyph: '🌫', label: 'Brume' },
      wind: { glyph: '🍃', label: 'Vent' },
      storm: { glyph: '⛈', label: 'Orage' },
    };
    return icons[code] ?? null;
  },
};
